apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: {{ include "services-haproxy.fullname" . }}
  annotations:
    {{- range $index, $element := .Values.endpoints }}
    endpoint{{$index}}: {{ $element.ip }}
    {{- end }}
  labels:
    {{- include "services-haproxy.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "services-haproxy.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        {{- range $index, $element := .Values.endpoints }}
        endpoint{{$index}}: {{ $element.ip }}
        {{- end }}
      labels:
        {{- include "services-haproxy.selectorLabels" . | nindent 8 }}
    spec:
      containers:
      - name: {{ .Chart.Name }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
        livenessProbe:
          failureThreshold: 8
          httpGet:
            host: localhost
            path: /healthz
            port: {{ .Values.listenPort }}
            scheme: HTTPS
        volumeMounts:
        - mountPath: /usr/local/etc/haproxy/haproxy.cfg
          name: haproxyconf
      hostNetwork: true
      volumes:
      - name: haproxyconf 
        configMap:
          name: haproxy-config
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}



