# This is a values file
harbor:
  persistence:
    enabled: true
    resourcePolicy: "keep"
    persistentVolumeClaim:
      registry:
        existingClaim: "registry"
        storageClass: "rook-cephfs"
        subPath: "registry"
        accessMode: ReadWriteMany
        size: 50Gi
