# https://github.com/hashicorp/vault-helm/blob/main/values.yaml
vault:
  global:
    enabled: false
  server:
    enabled: true
    standalone:
      enabled: true

replicaCount: 1

nameOverride: ""
fullnameOverride: ""

podAnnotations: {}

podSecurityContext: {}
  # fsGroup: 2000

securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

resources:
  limits:
    cpu: 50m
    memory: 64Mi
  requests:
    cpu: 50m
    memory: 64Mi
