## Reference: https://github.com/helm/chart-testing/blob/master/doc/ct_lint-and-install.md
# Don't add the 'debug' attribute, otherwise the workflow won't work anymore
# Only Used for the CT Install Stage
remote: origin
target-branch: main
chart-dirs:
  - charts/artifact-registry
  - charts/git-server
  - charts/kafka
  - charts/ntp
  - charts/vault
  - charts/squid
chart-repos:
  - kafka=https://strimzi.io/charts/
  - kafkaexport=https://prometheus-community.github.io/helm-charts
  - cp=https://confluentinc.github.io/cp-helm-charts/
  - vault=https://helm.releases.hashicorp.com
helm-extra-args: "--timeout 7200s"
validate-chart-schema: false
validate-maintainers: false
validate-yaml: true
exclude-deprecated: true
excluded-charts: []
