## Reference: https://github.com/helm/chart-testing/blob/master/doc/ct_lint-and-install.md
# Don't add the 'debug' attribute, otherwise the workflow won't work anymore
# Only Used for the CT Install Stage
remote: origin
target-branch: main
chart-dirs:
  - charts/argo-events
  - charts/argo-wf
  - charts/cache
  - charts/ceph
  - charts/cni
  - charts/dns-server
  - charts/git-server
  - charts/grafana
  - charts/ha-proxy
  - charts/harbor
  - charts/jaeger
  - charts/kafka
  - charts/lightvessel
  - charts/loadbalancer
  - charts/loki
  - charts/nidhogg
  - charts/ntp
  - charts/prometheus
  - charts/rook
  - charts/rook-helper
  - charts/thanos
  - charts/traefik
  - charts/vault
chart-repos:
  - argo=https://argoproj.github.io/argo-helm
  - repo=https://distributed-technologies.github.io/helm-repository/
  - stable=https://charts.helm.sh/stable
  - incubator=https://charts.helm.sh/incubator
helm-extra-args: "--timeout 600s"  
validate-chart-schema: false
validate-maintainers: false
validate-yaml: true
exclude-deprecated: true
excluded-charts: []
