kube-prometheus-stack:
  grafana:
    enabled: false

  # Disabled since we're using cortexs
  alertmanager:
    enable: false

  prometheus:
    enabled: true

    ## ref: https://github.com/prometheus-operator/prometheus-operator/blob/main/Documentation/api.md#prometheusspec
    prometheusSpec:

      # This is set from 10d to 2h because, Cause we should remote-write to cortex, and shouldn't need a large retention on prometheus itself
      retention: 2h

      remoteWrite:
        - url: http://cortex-distributor:8080/api/v1/push
