---
# A list of deployments, this allows for multiple deployments in the same chart.
deployments:
  # Name of the deployments - this is appended on the deployment and service name.
  podinfo:
    # Enable or disable this deployment
    enabled: false
    image:
      # The repository containing the image
      repository: ghcr.io/stefanprodan/podinfo
      # The image tag
      tag: 6.2.1

    # The amount of replicas wanted of this container
    replicaCount: 3

    # The volumes list defines what types of volumes to provide to the pod.
    # In general we only recommend using the following:
    # * configMaps https://kubernetes.io/docs/concepts/storage/volumes/#configmap
    # * secrets https://kubernetes.io/docs/concepts/storage/volumes/#secret
    # * emptyDir https://kubernetes.io/docs/concepts/storage/volumes/#emptydir
    # * persistentVolumeClaim (PVC) https://kubernetes.io/docs/concepts/storage/volumes/#persistentvolumeclaim
    volumes: []
    #  - name: cache-volume
    #    emptyDir: {}
    #  - name: configMap
    #    configMaps:
    #      name: foobar

    # The volumes defined above must be mounted in the pod on a specified path.
    volumeMounts: []
    #  - mountPath: /cache
    #    name: cache-volume

    # The ports on the pod and the equal port on the service and their protocol.
    ports:
      - podPortName: http
        podPort: 9898
        servicePortName: http
        servicePort: 80
        protocol: TCP

    networkPolicy:
      ingress: []
      egress: []

    # A list of secrets to fetch from the vault and mounted on the main pod.
    secrets:
      []
      # - name: token
      #   key: secret/tenant-foobar/token

# The configMap allows for storage of non secret configurations.
configMaps:
  []
  # - name: foobar
  #   content:
  #     debug: true
  #     bar-config.ini: |
  #       apiKey: qwertyuiop1234567890

# Persistent Volume claims allows for the creation of a volume that will persist even if the pod it's mounted on is destroyed.
persistentVolumeClaims:
# - name: foobar
#   size: 8Gi

kafkaTopics:
  # List of Kafka topics to create. You still need to configure the access to the topic in the 'access' block to give applications access to produce or consume to a topic.
  # In practice this generates a KafkaTopic resource in the namespace of the tenant which is the copied to the namespace of the Kafka cluster. This means that the KafkaTopic resource in the tenant namespace will not become Ready even tough its clone in Ready.
  # Requirements: The name of the topics must include the tenants namespace name as prefix. This is to avoid naming collisions between different tenants' Kafka topics.
  #
  #
  # Note: The example shows the only supported configuration fields of a Kafka topic with the default values.
  # If you need to do more advanced configuration of a Kafka topics, please contact the maintainers, so they can add support for the requested configuration field.
  create: []
  #  - name: "example-topic"                  #(required)
  #    replicas: 3
  #    partitions: 1
  #    retention:
  #      ms: 604800000                        #7days
  #      bytes: -1                            #No byte retention
  #  List of Kafka topics to access.
  access: []
  #  - name: "tenant-test-topic"              #(required)
  #    applicationName: "kafka-test-produce"  #(required)
  #    namespace: "tenant-test"               #(required)
  #    produce: false                         #(required)
  #    consume: false                         #(required)
