# Allows for renaming of the chart, this is advised since the pods would include 'tenant-base' as the name otherwise.
fullnameOverride: foobar

# A list of deployments, this allows for multiple deployments in the same chart.
deployments:
  # Name of the deployments - this is appended on the deployment and service name.
  - name: podinfo
    image:
      # The repository containing the image
      repository: ghcr.io/stefanprodan/podinfo
      # The pullPolicy
      # * IfNotPresent - If the image is not cached on the device
      # * Always       - Will always try to fetch the newest image
      # * Never        - Will not try to fetch an image - if image is not present on the machine startup fails
      pullPolicy: IfNotPresent
      # The image tag
      tag: 6.2.1

    # The name of the secret that contains the credentials for private image repositories.
    imagePullSecrets:
      - name: acr-token

    # The amount of replicas wanted of this container
    replicaCount: 3

    # Liveness probes are used to determine what state the application is in, and allows k8s to remedy a broken state, by e.g. restarting the pod.
    livenessProbe:
      httpGet:
        path: /healthz
        port: 9898

    # Readiness probes lets k8s know when a pod is ready to accept traffic.
    readinessProbe:
      httpGet:
        path: /healthz
        port: 9898

    # The volumes list defines what types of volumes to provide to the pod.
    # In general we only recommend using the following:
    # * configMaps https://kubernetes.io/docs/concepts/storage/volumes/#configmap
    # * secrets https://kubernetes.io/docs/concepts/storage/volumes/#secret
    # * emptyDir https://kubernetes.io/docs/concepts/storage/volumes/#emptydir
    # * persistentVolumeClaim (PVC) https://kubernetes.io/docs/concepts/storage/volumes/#persistentvolumeclaim
    volumes: []
    #  - name: cache-volume
    #    emptyDir: {}
    #  - name: configMap
    #    configMaps:
    #      name: foobar

    # The volumes defined above must be mounted in the pod on a specified path.
    volumeMounts: []
    #  - mountPath: /cache
    #    name: cache-volume

    # This allows the user to define the resources needed to run the deployment.
    # We usually recommend not to specify default resources and to leave this as a conscious
    # choice for the user.
    resources:
      {}
      # limits:
      #   cpu: 100m
      #   memory: 128Mi
      # requests:
      #   cpu: 100m
      #   memory: 128Mi

    # The ports on the pod and the equal port on the service and their protocol.
    ports:
      - podPortName: http
        podPort: 9898
        servicePortName: http
        servicePort: 80
        protocol: TCP

    networkPolicy:
      ingress: []
      egress: []

    # A list of secrets to fetch from the vault and mounted on the main pod.
    secrets:
      []
      # - name: token
      #   key: secret/tenant-foobar/token

# The configMap allows for storage of non secret configurations.
configMaps:
  []
  # - name: foobar
  #   content:
  #     debug: true
  #     bar-config.ini: |
  #       apiKey: qwertyuiop1234567890

# Bucket claims allows for the creation of a s3 object storage,
# The bucketClaim creates a secret and configMap that needs to be mounted on the pod that will use it.
# The name of the secret and configMap is <name>-bucket.
bucketClaims:
  # - name: foobar

# Persistent Volume claims allows for the creation of a volume that will persist even if the pod it's mounted on is destroyed.
persistentVolumeClaims:
  # - name: foobar
  #   size: 8Gi
  #   # Optional
  #   storageClassName: standard

# This is a reference to the clusterSecretStore located on the cluster.
secretStore:
  name: default
  kind: ClusterSecretStore

# List of Kafka topics to create.
# Note: The example shows the only supported configuration fields of a Kafka topic with the default values.
# If you need to do more advanced configuration of a Kafka topics, please contact the maintainers, so they can add support for the requested configuration field.
kafkaTopics: []
#  - name: "example-topic"  #(required)
#    replicas: 3
#    partitions: 1
#    retention:
#      ms: 604800000 # 7 days
#      bytes: -1
