apiVersion: v1
kind: Secret
metadata:
  name: {{ include "chart.fullname" . }}
  labels:
    {{- include "chart.labels" . | nindent 4 }}
stringData:
{{- range $key, $val := .Values.certificates }}
  {{ $key }}: | {{ $val | nindent 4 }}
{{- end }}
