env: test
replicaCount: 1
nginx:
  image:
    repository: git-server-nginx
    pullPolicy: IfNotPresent
    # Overrides the image tag whose default is the chart appVersion.
    tag: "0.1.27"

fcgi:
  image:
    repository: ghcr.io/distributed-technologies/helm-charts/git-server
    pullPolicy: IfNotPresent
    tag: "0.2.2"

service:
  type: ClusterIP
  port: 80

affinity: {}
dataVolume:
  size: 1G
  storageClass: standard
  accessMode: ReadWriteOnce

# The volume for holding the repos. Required for HA.
gitServerReposVolume:
  emptyDir: {}
# All git repositories created
repos:
  - git-test-project
