env: test
replicaCount: 1
nginx:
  image:
    repository: nginx
    pullPolicy: IfNotPresent
    tag: "1.21.4"

fcgi:
  image:
    repository: ghcr.io/distributed-technologies/helm-charts/git-server
    pullPolicy: IfNotPresent
    tag: ""

service:
  type: ClusterIP
  port: 80

affinity: {}
dataVolume:
  size: 1G
  storageClass: standard
  accessMode: ReadWriteOnce

# The volume for holding the repos. Required for HA.
gitServerReposVolume:
  emptyDir: {}
# All git repositories created
repos: []
