env: test
replicaCount: 1

image:
  repository: ghcr.io/distributed-technologies/services-git-server
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: "feature-git-server"

service:
  type: ClusterIP
  port: 80

affinity: {}

dataVolume:
  size: 1G
  storageClass: standard
  accessMode: ReadWriteOnce

# The volume for holding the repos. Required for HA.
gitServerReposVolume:
  emptyDir: {}
# All git repositories created
repos:
  - git-test-project
