env: test
replicaCount: 1
nginx:
  image:
    repository: nginx
    pullPolicy: IfNotPresent
    tag: "1.21.4"

fcgi:
  image:
    repository: ghcr.io/distributed-technologies/helm-charts/git-server
    pullPolicy: IfNotPresent
    tag: 0.2.4

service:
  type: ClusterIP
  port: 80

affinity: {}
pvc:
  # If enabled a PVC will be created
  enabled: true
  size: 1G
  storageClass: standard
# Defining a volumeName will pind the created PVC to a specific PersistentVolume with the name.
# volumeName: git-server
  accessMode: ReadWriteOnce
