image:
  repository: haproxy
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: "2.1.4"

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""
nodeSelector: {}

# Tolerate being scheduled on tainted master nodes
tolerations:
- key: node-role.kubernetes.io/master
  operator: Exists
  effect: NoSchedule

# Schedule only on master nodes
affinity:
  nodeAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
      nodeSelectorTerms:
      - matchExpressions:
        - key: node-role.kubernetes.io/control-plane
          operator: Exists

# Endpoints that trafic is loadbalanced to
endpoints:
  - ip: 192.168.1.140
    port: 6443
# The port to listen on for trafic
listenPort: 4200
