replicaCount: 2

image:
  repository: ghcr.io/distributed-technologies/helm-charts/ntp
  pullPolicy: Always
  # Overrides the image tag whose default is the chart appVersion.
  tag: "0.1.4"

ntp: {}
  # Override the NTP server (ex: a internal NTP server)
  # server: pool.ntp.org

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

podAnnotations: {}

podSecurityContext:
  runAsNonRoot: true

securityContext:
  capabilities:
    add:
      - SYS_TIME
      - NET_BIND_SERVICE
    drop:
      - ALL

service:
  type: ClusterIP
  port: 123
  protocol: UDP

resources:
  limits:
    cpu: 100m
    memory: 16Mi
  requests:
    cpu: 25m
    memory: 16Mi
