{{- define "limitRange" }}
  {{- $root := . }}
  {{- range $limitRangePath, $_ := .Files.Glob "**/**/limit-range.yaml" }}
    {{- $configPath := printf "%s/config.yaml" ($limitRangePath | dir) }}
    {{- $config := $root.Files.Get $configPath | fromYaml }}
    {{- $appEnabledInConfig := 0 }}
    {{- range $config.apps }}
      {{- if get $root.Values.applications .name }}
        {{- $appEnabledInConfig = 1 }}
      {{- end }}
    {{- end }}
    {{- if $appEnabledInConfig }}
---
apiVersion: v1
kind: LimitRange
metadata:
  name: {{ template "helper.name" (dict "context" $root "name" $config.name ) }}-limit-range
  namespace: {{ $config.namespace }}
spec:
{{- $limitRange := $root.Files.Get $limitRangePath }}
{{ tpl $limitRange $root | indent 2 }}
    {{- end }}
  {{- end }}
{{- end }}
