{{- define "namespace" }}
  {{- $root := . }}
  {{ $namespaces := list }}
  {{- range $configPath, $_ := .Files.Glob "**/**/config.yaml" }}
    {{- $config := $root.Files.Get $configPath | fromYaml }}
    {{- if not $config.destinationServer }}
      {{- $appEnabledInConfig := 0 }}
      {{- range $config.apps }}
        {{- if get $root.Values.applications .name -}}
          {{- $appEnabledInConfig = 1 -}}
        {{- end -}}
      {{- end }}
      {{- if $appEnabledInConfig }}
        {{- if not (has $config.namespace $namespaces) }}
        {{- $namespaces = append $namespaces $config.namespace }}
---
apiVersion: v1
kind: Namespace
metadata:
  name: {{ template "helper.name" (dict "context" $root "name" $config.namespace ) }}
  labels:
{{- if $config.namespaceLabels }}
{{ $config.namespaceLabels | toYaml | indent 4 }}
{{- end }}
      {{- end }}
    {{- end }}
  {{- end }}
{{- end }}
{{- end }}
