{{- define "project" }}
  {{- $root := . }}
  {{- range $configPath, $_ := .Files.Glob "**/**/config.yaml" }}
    {{- $config := $root.Files.Get $configPath | fromYaml }}
    {{- $appEnabledInConfig := 0 }}
    {{- range $config.apps }}
      {{- if get $root.Values.applications .name -}}
        {{- $appEnabledInConfig = 1 -}}
      {{- end }}
    {{- end }}
    {{- if $appEnabledInConfig }}
---
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: {{ template "helper.name" (dict "context" $root "name" $config.name ) }}
  namespace: {{ $root.Release.Namespace }}
  # Finalizer that ensures that project is not deleted until it is not referenced by any application
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
{{- $configFilePath := printf "%s/project.yaml" ($configPath | dir) }}
{{- $configFile := $root.Files.Get $configFilePath }}
{{ tpl $configFile $root | indent 2 }} 
    {{- end }}
  {{- end }}
{{ end }}
