{{- define "resourceQuota" }}
  {{- $root := . }}
  {{- range $resourceQuotaPath, $_ := .Files.Glob "**/**/resource-quota.yaml" }}
    {{- $configPath := printf "%s/config.yaml" ($resourceQuotaPath | dir) }}
    {{- $config := $root.Files.Get $configPath | fromYaml }}
    {{- $appEnabledInConfig := 0 }}
    {{- range $config.apps }}
      {{- if get $root.Values.applications .name }}
        {{- $appEnabledInConfig = 1 }}
      {{- end }}
    {{- end }}
    {{- if $appEnabledInConfig }}
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: {{ template "helper.name" (dict "context" $root "name" $config.name ) }}
  namespace: {{ $config.namespace }}
spec: 
{{- $resourceQuota := $root.Files.Get $resourceQuotaPath }}
{{ tpl $resourceQuota $root | indent 2 }}
    {{- end }}
  {{- end }}
{{- end }}
