apiVersion: v2
name: thanos
description: A Helm chart for Kubernetes
type: application
version: v0.1.0

dependencies:
- name: thanos
  version: "0.4.5"
  repository: "https://kubernetes-charts.banzaicloud.com"
  condition: thanos.enabled
