apiVersion: v2
name: thanos
description: A Helm chart for Kubernetes
type: application
version: 0.1.0

dependencies:
- name: thanos
  version: "7.0.1"
  repository: "https://charts.bitnami.com/bitnami"
