promtail:
  initContainer:
    # -- Specifies whether the init container for setting inotify max user instances is to be enabled
    enabled: true
    # -- The inotify max user instances to configure
    # The reason this has changed from 128 is that under testing the error
    # `To many open files` began to accure quite frequently and after some searching
    # I found a Github Issue digging into the problem[1].
    # In short the conclusion was the `Raising fs.inotify.max_user_instances higher than
    # the container count should allow promtail to operate fine`
    #
    # [1] https://github.com/grafana/loki/issues/4740
    fsInotifyMaxUserInstances: 512

  serviceMonitor:
    enabled: true
    labels:
      instance: primary

  config:
    lokiAddress: http://loki-loki-distributed-distributor:3100/loki/api/v1/push
