env: prod
helmServer:
  replicaCount: 1
  image:
    repository: nginx
    pullPolicy: Always
    tag: 1.21.3
  service:
    type: ClusterIP
    port: 80
  resources:
    limits:
      cpu: 100m
      memory: 128Mi
    requests:
      cpu: 100m
      memory: 128Mi
  affinity: {}
  dataVolume:
    size: 1G
    storageClass: standard
    accessMode: ReadWriteOnce

imageRegistry:
  replicaCount: 1
  image:
    repository: registry
    pullPolicy: Always
    tag: "2.7"
  service:
    type: ClusterIP
    port: 443
  resources:
    limits:
      cpu: 100m
      memory: 128Mi
    requests:
      cpu: 100m
      memory: 128Mi
  affinity: {}
  keysVolume:
    type: emptyDir
    config: {}
  dataVolume:
    size: 1G
    storageClass: standard
    accessMode: ReadWriteOnce
