yggdrasil:
  repoURL: "https://github.com/distributed-technologies/yggdrasil.git"
  targetRevision: "main"

installCNI: true

lb-proxy:
  enabled: false

argo-cd-proxy-chart:
  argo-cd:
    controller:
      replicas: 3
      env:
        - name: "ARGOCD_CONTROLLER_REPLICAS"
          value: "3"
      enableStatefulSet: true
    redis-ha:
      enabled: true
    redis:
      enabled: false
    server:
      replicas: 3
      config:
        resource.customizations: |
          admissionregistration.k8s.io/MutatingWebhookConfiguration:
            ignoreDifferences: |
              jsonPointers:
              - /webhooks/0/clientConfig/caBundle
          admissionregistration.k8s.io/ValidatingWebhookConfiguration:
            ignoreDifferences: |
              jsonPointers:
              - /webhooks/0/clientConfig/caBundle
              - /webhooks/0/namespaceSelector/matchExpressions/2
          networking.k8s.io/Ingress:
            health.lua: |
              hs = {}
              hs.status = "Healthy"
              return hs
