{{- range .Values.connector.topics }}
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaTopic
metadata:
  name: {{ .name }}
  labels:
    strimzi.io/cluster: my-cluster
spec: 
  topicName: {{ .name }}
  partitions: {{  $.Values.connector.topic_partitions }}
  replicas: {{  $.Values.connector.topic_replicas }}
---
{{ end }}
