---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nidhogg
  namespace: {{ .Release.Namespace }}
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: yggdrasil
  source:
    repoURL: {{ .Values.yggdrasil.repoURL }}
    targetRevision: {{ .Values.yggdrasil.targetRevision }}
{{- if ( hasSuffix ".git" .Values.yggdrasil.repoURL ) }}
    path: "nidhogg"
{{- else }}
    chart: "nidhogg"
{{- end }}
    helm:
      version: v3
      values: |
        nidhogg:
          yggdrasil:
{{ toYaml .Values.yggdrasil | indent 12 }}
  destination:
    server: https://kubernetes.default.svc
    namespace: {{ .Release.Namespace }}
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
