apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "services-dns-server.fullname" . }}
  labels:
    {{- include "services-dns-server.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "services-dns-server.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "services-dns-server.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.name }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            {{- range $name, $config := .Values.service.ports }}
            - name: {{ $name }}
              containerPort: {{ $config.port }}
              protocol: {{ $config.protocol }}
            {{- end }}
          volumeMounts:
            - name: config-vol
              mountPath: /Corefile
              subPath: Corefile
            - name: config-vol
              mountPath: /db.garagen
              subPath: db.garagen
      volumes:
        - name: config-vol
          configMap:
            name: {{ include "services-dns-server.fullname" . }}-configmap
