# The definitions in _helpers.tpl does not work in ranges because it changes the scope
{{- $fullname := include "services-dns-server.fullname" . -}}
{{- $labels := include "services-dns-server.labels" . -}}
{{- $selectorLabels := include "services-dns-server.selectorLabels" . }}
{{- $root := .}}

{{- range $name, $config := .Values.service.ports }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ $fullname }}-{{ $config.protocol | lower }}
  labels:
    {{- $labels | nindent 4 }}
  annotations:
    metallb.universe.tf/allow-shared-ip: "{{ $fullname }}-sharing-key"
spec:
  type: {{ $root.Values.service.type }}
  {{- if $root.Values.service.loadBalancerIP }}
  loadBalancerIP: {{ $root.Values.service.loadBalancerIP }}
  {{- end }}
  ports:
    - port: {{ $config.port }}
      targetPort: {{ $name }}
      protocol: {{ $config.protocol }}
      name: {{ $name }}
      {{- if $config.nodePort }}
      nodePort: {{ $config.nodePort }}
      {{- end }}
  selector:
      {{- $selectorLabels | nindent 4 }}
{{- end }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ $fullname }}-nodeport
  labels:
    {{- $labels | nindent 4 }}
spec:
  type: NodePort
  ports:
    - port: 53
      targetPort: dns-udp
      protocol: UDP
      name: dns-udp-nodeport
      nodePort: 30053
  selector:
      {{- $selectorLabels | nindent 4 }}
