{{- range $name, $val := .Values.deployments }}
{{- if .enabled }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ printf "%s-%s" $.Release.Name $name }}
  labels:
    {{- include "chart.labels" (dict "name" $name "values" $val "root" $) | nindent 4 }}
spec:
  replicas: {{ .replicaCount }}
  selector:
    matchLabels:
      {{- include "chart.selectorLabels" (dict "name" $name) | nindent 6 }}
  template:
    metadata:
      {{- with .podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "chart.selectorLabels" (dict "name" $name) | nindent 8 }}
    spec:
      {{- include "chart.topologySpreadConstrains" (dict "root" $ "values" $val "name" $name) | nindent 6 }}
      imagePullSecrets:
        - name: registry-token
      containers:
        - name: {{ $name }}
          securityContext:
            {{- toYaml .securityContext | nindent 12 }}
          image: {{ printf "%s:%s" .image.repository .image.tag }}
          imagePullPolicy: IfNotPresent
          ports:
          {{- range .ports }}
            - name: {{ .podPortName }}
              containerPort: {{ .podPort }}
              protocol: {{ .protocol }}
          {{- end }}
          livenessProbe:
            httpGet:
              path: /healthz
              port: 9898
          readinessProbe:
            httpGet:
              path: /healthz
              port: 9898
          resources:
            {{- toYaml .resources | nindent 12 }}
          volumeMounts:
            {{- toYaml .volumeMounts | nindent 12 }}
          envFrom:
          {{- range .secrets }}
          - secretRef:
              name: {{ printf "%s-%s" $.Release.Name .name }}
          {{- end }}
          {{- range .configMaps }}
          - configMapRef:
              name: {{ printf "%s-%s" $.Release.Name .name }}
          {{- end }}
      volumes:
        {{- toYaml .volumes | nindent 8 }}
{{ end -}}
{{- end }}
