{{- range $name, $val := .Values.deployments }}
{{- if .enabled }}

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ printf "%s-%s" (include "chart.fullname" $) $name }}
  labels:
    {{- include "chart.labels" $ | nindent 4 }}
spec:
  replicas: {{ .replicaCount }}
  selector:
    matchLabels:
      {{- include "chart.selectorLabels" $ | nindent 6 }}
      app.kubernetes.io/app: {{ $name }}
  template:
    metadata:
      {{- with .podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "chart.selectorLabels" $ | nindent 8 }}
        app.kubernetes.io/app: {{ $name }}
    spec:
      {{- include "chart.topologySpreadConstrains" (dict "root" $ "values" $val "name" $name) | nindent 6 }}
      imagePullSecrets:
        - name: registry-token
      containers:
        - name: {{ $name }}
          securityContext:
            {{- toYaml .securityContext | nindent 12 }}
          image: {{ printf "%s:%s" .image.repository .image.tag }}
          imagePullPolicy: IfNotPresent
          ports:
          {{- range .ports }}
            - name: {{ .podPortName }}
              containerPort: {{ .podPort }}
              protocol: {{ .protocol }}
          {{- end }}
          livenessProbe:
            httpGet:
              path: /healthz
              port: 9898
          readinessProbe:
            httpGet:
              path: /healthz
              port: 9898
          resources:
            {{- toYaml .resources | nindent 12 }}
          volumeMounts:
            {{- toYaml .volumeMounts | nindent 12 }}
          {{- with .secrets }}
          envFrom:
            {{- range . }}
            - secretRef:
                name: {{ printf "%s-%s" (include "chart.fullname" $) $name }}
            {{- end }}
          {{- end }}
      volumes:
        {{- toYaml .volumes | nindent 8 }}
{{ end -}}
{{- end }}
