{{- range $deploymentName, $val := .Values.deployments }}
{{- if .enabled }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ printf "%s-%s" $.Release.Name $deploymentName }}
  labels:
    {{- include "chart.labels" (dict "name" $deploymentName "values" $val "root" $) | nindent 4 }}
spec:
  replicas: {{ .replicaCount }}
  selector:
    matchLabels:
      {{- include "chart.selectorLabels" (dict "name" $deploymentName) | nindent 6 }}
  template:
    metadata:
      annotations:
        {{- /* To ensure pods are recreated when a configmap changes that the pod mounts, we annotate the pods with the checksums of the configmaps. */}}
          {{- range $_, $allConfigMap := $.Values.configMaps -}}
            {{- range $_, $deploymentConfigMap := $val.configMaps -}}
              {{- if eq $allConfigMap.name $deploymentConfigMap.name }}
                {{- printf "%s/%s: %s" "checksum/configmap" $allConfigMap.name ($allConfigMap | toYaml | toString | sha256sum) | nindent 8 }}
              {{- end -}}
            {{- end -}}
          {{- end }}
      labels:
        {{- include "chart.selectorLabels" (dict "name" $deploymentName) | nindent 8 }}
    spec:
      {{- include "chart.topologySpreadConstrains" (dict "root" $ "values" $val "name" $deploymentName) | nindent 6 }}
      imagePullSecrets:
        - name: registry-token
      containers:
        - name: {{ $deploymentName }}
          securityContext:
            {{- toYaml .securityContext | nindent 12 }}
          image: {{ printf "%s:%s" .image.repository .image.tag }}
          imagePullPolicy: IfNotPresent
          ports:
          {{- range .ports }}
            - name: {{ .podPortName }}
              containerPort: {{ .podPort }}
              protocol: {{ .protocol }}
          {{- end }}
          livenessProbe:
            httpGet:
              path: /healthz
              port: 9898
          readinessProbe:
            httpGet:
              path: /healthz
              port: 9898
          resources:
            {{- toYaml .resources | nindent 12 }}
          volumeMounts:
            {{- range .pvcs }}
            - name: {{ .name }}-volume
              mountPath: {{ .path }}
            {{- end }}
          envFrom:
            {{- range .secrets }}
            - secretRef:
                name: {{ printf "%s-%s" $.Release.Name .name }}
            {{- end }}
            {{- range .configMaps }}
            - configMapRef:
                name: {{ printf "%s-%s" $.Release.Name .name }}
            {{- end }}
      volumes:
        {{- range .pvcs }}
        - name: {{ .name }}-volume
          persistentVolumeClaim:
            claimName: {{ printf "%s-%s" $.Release.Name .name }}
        {{- end }}
{{ end -}}
{{- end }}
