{{- range .Values.secrets }}
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ include "chart.fullname" $ }}-{{ .name }}
  labels:
    {{- include "chart.labels" $ | nindent 4 }}
spec:
  refreshInterval: "5m"
  secretStoreRef:
    name: {{ $.Values.secretStore.name }}
    kind: {{ $.Values.secretStore.kind }}
  target:
    name: {{ include "chart.fullname" $ }}-{{ .name }}
  dataFrom:
  - extract:
      key: {{ .key }}
{{- end }}
