{{- range $deploymentName, $val := .Values.deployments }}
{{- $fullName := (printf "%s-%s" $.Release.Name $deploymentName) }}
{{- if .enabled }}
{{- if .ingress }}
{{- if .ingress.host }}
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: {{ $fullName }}
  namespace: {{ $.Release.Namespace }}
spec:
  routes:
    - kind: Rule
      match: "Host(`{{ .ingress.host }}`) && Path(`/{{ required "An ingress path is required" .ingress.path }}`)"
      services:
        - namespace: {{ $.Release.Namespace }}
          name: {{ .ingress.serviceName }}
          port: {{ .ingress.port }}
      {{- if .ingress.path }}
      middlewares:
        - name: stripprefix-{{ required "An ingress path is required" .ingress.path }}
          namespace: {{ $.Release.Namespace }}
      {{- end }}
  tls:
    secretName: {{ required "A valid ingress secretName is required" .ingress.secretName }}
{{- end -}}
{{- end -}}
{{- end -}}
{{- end -}}
