{{- range $deploymentName, $val := .Values.deployments }}
{{- $fullName := (printf "%s-%s" $.Release.Name $deploymentName) }}
{{- if .enabled }}
{{- if .ingress }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: ingress-access
  namespace: {{ $.Release.Namespace }}
spec:
  podSelector: {}
  policyTypes:
    - Ingress
    - Egress
  ingress:
    - from:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: traefik
          podSelector:
            matchLabels:
              app.kubernetes.io/name: traefik
  egress: []
{{- end }}
{{- end }}
{{- end }}
