{{- range .Values.kafkaTopics }}
# https://strimzi.io/docs/operators/latest/configuring.html#type-KafkaTopic-reference
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaTopic
metadata:
  name: {{ .name }}
  labels:
    strimzi.io/cluster: my-cluster
spec: 
  topicName: {{ .name }}
  partitions: {{ .partitions }}
  replicas: {{  .replicas }}
  config: 
    # https://kafka.apache.org/documentation/#topicconfigs
    retention.ms: {{ .retention.ms | default  604800000 }} # 7 days
    retention.bytes: {{ .retention.bytes | default -1 }}
---
{{- end }}
