{{- range .Values.kafkaTopics.create }}
{{- $fullName := (printf "%s-%s" $.Release.Namespace .name) }}
# https://strimzi.io/docs/operators/latest/configuring.html#type-KafkaTopic-reference
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaTopic
metadata:
  name: {{ $fullName}}
  labels:
    {{- include "chart.selectorLabels" (dict "name" $fullName) | nindent 4 }}
    strimzi.io/cluster: my-cluster
spec:
  topicName: {{ $fullName}}
  partitions: {{ .partitions }}
  replicas: {{  .replicas }}
  config:
    # https://kafka.apache.org/documentation/#topicconfigs
    {{- $retention := .retention | default dict }}
    retention.ms: {{ $retention.ms | default  604800000 }}
    retention.bytes: {{ $retention.bytes | default -1 }}
---
{{- end }}
