{{- range $deploymentName, $val := .Values.deployments }}
{{- $fullName := (printf "%s-%s" $.Release.Name $deploymentName) }}
{{- if .enabled }}
{{- if .networkPolicy }}
{{- if .networkPolicy.egress }}
---
apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  labels:
    {{- include "chart.labels" (dict "name" $fullName "values" $val "root" $) | nindent 4 }}
  name: {{ $fullName }}-dns-access 
spec:
  egress:
    - toEndpoints:
      - matchLabels:
          "k8s:io.kubernetes.pod.namespace": kube-system
          "k8s:k8s-app": kube-dns
      toPorts:
        - ports:
          - port: "53"
            protocol: TCP
          - port: "53"
            protocol: UDP
  endpointSelector:
    matchLabels:
      app.kubernetes.io/instance: {{ $.Release.Name }}-{{ $deploymentName }}
      app.kubernetes.io/name: {{ $.Release.Name }}-{{ $deploymentName }}
{{- end }}
{{- end }}
{{- end }}
{{- end }}
