{{- range $i, $val := .Values.persistentVolumeClaims }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .name }}
spec:
  accessModes:
    - ReadWriteMany
  volumeMode: Filesystem
  resources:
    requests:
      storage: {{ .size }}
  storageClassName: {{ .storageClassName | default "ceph-block"}}
{{ end -}}
