{{- range $name, $val := .Values.deployments }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ printf "%s-%s" (include "chart.fullname" $) $name }}
  labels:
    {{- include "chart.labels" $ | nindent 4 }}
spec:
  ports:
{{- range .ports }}
    - port: {{ .servicePort }}
      name: {{ .servicePortName }}
      targetPort: {{ .podPortName }}
      protocol: {{ .protocol }}
{{- end }}
  selector:
    {{- include "chart.selectorLabels" $ | nindent 4 }}
    app.kubernetes.io/app: {{ $name }}
{{ end -}}
