{{- range $deploymentName, $val := .Values.deployments }}
{{- $fullName := (printf "%s-%s" $.Release.Name $deploymentName) }}
{{/** If the deployment is enabled, ports are defined and ports is not an empty list **/}}
{{- if and .enabled (and .ports (not (eq (len .ports) 0))) }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ $fullName }}
  labels:
    {{- include "chart.labels" (dict "name" $fullName "values" $val "root" $) | nindent 4 }}
spec:
  ports:
{{- range .ports }}
    - port: {{ .servicePort }}
      name: {{ .servicePortName }}
      targetPort: {{ .podPortName }}
      protocol: {{ .protocol }}
{{- end }}
  selector:
    {{- include "chart.selectorLabels" (dict "name" $fullName) | nindent 6 }}
{{ end -}}
{{ end -}}
