{{- range $name, $val := .Values.deployments }}
{{- if .enabled }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ printf "%s-%s" $.Release.Name $name }}
  labels:
    {{- include "chart.labels" (dict "name" $name "values" $val "root" $) | nindent 4 }}
spec:
  ports:
{{- range .ports }}
    - port: {{ .servicePort }}
      name: {{ .servicePortName }}
      targetPort: {{ .podPortName }}
      protocol: {{ .protocol }}
{{- end }}
  selector:
    {{- include "chart.selectorLabels" (dict "name" $name) | nindent 6 }}
{{ end -}}
{{ end -}}
