{{- range $deploymentName, $val := .Values.deployments }}
{{- $fullName := (printf "%s-%s" $.Release.Name $deploymentName) }}
{{/** If the deployment is enabled, ports are defined and ports is not an empty list **/}}
{{- if and .enabled (and .ports (not (eq (len .ports) 0))) }}
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ $fullName }}
  labels:
    {{- include "chart.labels" (dict "name" $fullName "values" $val "root" $) | nindent 4 }}
spec:
  endpoints:
    {{- range .ports }}
  - interval: 30s
    port: {{ .servicePortName }}
    scrapeTimeout: 25s
  {{- end }}
  namespaceSelector:
    matchNames:
    - {{ $.Release.Namespace }}
  selector:
    matchLabels:
      {{- include "chart.labels" (dict "name" $fullName "values" $val "root" $) | nindent 6 }}
{{ end -}}
{{- end }}
