apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "chart.fullname" . }}
  labels:
    {{- include "chart.labels" . | nindent 4 }}
data:
  haproxy.cfg: |
    # https://cbonte.github.io/haproxy-dconv/
    global
        maxconn 10000
        log     stdout format raw local0
        user    haproxy

    resolvers resolv
        parse-resolv-conf

    listen main
        bind    :8080
        bind    [::]:8080
        mode    tcp
        log     global
        option  tcplog
        option  dontlognull

        timeout client  30s
        timeout connect 5s
        timeout server  30s
        timeout queue   30s
        {{- if and (not .Values.config.clusterProxy) (not .Values.config.externalProxy) -}}
        {{ fail "config.clusterProxy or config.externalProxy must be specified" }}
        {{- end -}}
        {{- if .Values.config.clusterProxy }}
        server  clusterproxy  {{ required "config.clusterProxy must be set" .Values.config.clusterProxy }}   check init-addr libc,none resolvers resolv
        {{- end -}}
        {{- if .Values.config.externalProxy }}
        server  externalproxy {{ required "config.externalProxy must be set" .Values.config.externalProxy }} check init-addr libc,none resolvers resolv backup
        {{- end -}}
