apiVersion: kafka.strimzi.io/v1beta2
kind: Kafka
metadata:
  name: {{ .Values.cluster.name }}
  labels:
    app: strimzi
spec:
  kafka:
    template:
      pod:
        metadata:
          labels:
            app: kafka-broker
        affinity:
          podAntiAffinity:
            preferredDuringSchedulingIgnoredDuringExecution:
              - weight: 100
                podAffinityTerm:
                  labelSelector:
                    matchLabels:
                      app: kafka-broker
                  topologyKey: "kubernetes.io/hostname"
    replicas: {{ .Values.cluster.kafka.replicas }}
    version: {{ .Values.cluster.kafka.version }} 
    logging: 
      type: inline
      loggers:
        kafka.root.logger.level: "INFO"
    {{- if .Values.cluster.kafka.resources }}
    resources: {{- .Values.cluster.kafka.resources | toYaml | nindent 6 }}
    {{- end }}
    readinessProbe: 
      initialDelaySeconds: 15
      timeoutSeconds: 5
    livenessProbe:
      initialDelaySeconds: 15
      timeoutSeconds: 5
    jvmOptions: 
      -Xms: 8192m
      -Xmx: 8192m
    listeners: {{ .Values.cluster.kafka.listeners | toYaml | nindent 6 }}
    authorization: 
      type: simple
      superUsers: # TODO add authentication
        - ANONYMOUS
    config: 
      log.message.format.version: {{ .Values.cluster.kafka.version }}
      inter.broker.protocol.version: {{ .Values.cluster.kafka.version }}
    {{- with .Values.cluster.kafka.config }}
      auto.create.topics.enable: {{ .autoCreateTopicEnable }}
      log.retention.hours: {{ .logRetentionHours }}
      log.roll.hours: {{ .logRollHours }}
      offsets.topic.replication.factor: {{ min $.Values.cluster.kafka.replicas (default 3 .offsetsTopicReplicationFactor) }}
      transaction.state.log.replication.factor: {{ min $.Values.cluster.kafka.replicas (default 3 .transactionStateLogReplicationFactor ) }}
      transaction.state.log.min.isr: {{ min $.Values.cluster.kafka.replicas (default 2 .transactionStateLogMinIsr) }}
    {{- end }}
      ssl.cipher.suites: "TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384" 
      ssl.enabled.protocols: "TLSv1.2"
      ssl.protocol: "TLSv1.2"
    storage:
      type: persistent-claim 
      size: {{ .Values.cluster.kafka.storage.size }}
      class: {{ .Values.cluster.kafka.storage.class }} 
    metricsConfig:
      type: jmxPrometheusExporter
      valueFrom:
        configMapKeyRef:
          name: kafka-metrics
          key: kafka-metrics-config.yml
  zookeeper:
    template:
      pod:
        metadata:
          labels:
            app: kafka-zookeeper
        affinity:
          podAntiAffinity:
            preferredDuringSchedulingIgnoredDuringExecution:
              - weight: 100
                podAffinityTerm:
                  labelSelector:
                    matchLabels:
                      app: kafka-zookeeper
                  topologyKey: "kubernetes.io/hostname"
    replicas: {{ .Values.cluster.zookeeper.replicas }}
    logging:
      type: inline
      loggers:
        zookeeper.root.logger: "INFO"
    {{- if .Values.cluster.zookeeper.resources }}
    resources: {{- .Values.cluster.zookeeper.resources | toYaml | nindent 6 }}
    {{- end }}
    jvmOptions:
      -Xms: 4096m
      -Xmx: 4096m
    storage:
      type: persistent-claim
      size: {{ .Values.cluster.zookeeper.storage.size }}
      class: {{ .Values.cluster.zookeeper.storage.class }}
    metricsConfig:
      type: jmxPrometheusExporter
      valueFrom:
        configMapKeyRef:
          name: kafka-metrics
          key: zookeeper-metrics-config.yml
  entityOperator: 
    tlsSidecar: 
      {{- if .Values.cluster.entityOperator.tlsSidecar.resources }}
      resources: {{- .Values.cluster.entityOperator.tlsSidecar.resources | toYaml | nindent 8 }}
      {{- end }}
    topicOperator:
      watchedNamespace: {{ .Release.Namespace }}
      reconciliationIntervalSeconds: 60
      logging: 
        type: inline
        loggers:
          rootLogger.level: "INFO"
      {{- if .Values.cluster.entityOperator.topicOperator.resources }}
      resources: {{- .Values.cluster.entityOperator.topicOperator.resources | toYaml | nindent 8 }}
      {{- end }}
    userOperator:
      watchedNamespace: {{ .Release.Namespace }}
      reconciliationIntervalSeconds: 60
      logging:
        type: inline
        loggers:
          rootLogger.level: INFO
      {{- if .Values.cluster.entityOperator.userOperator.resources }}
      resources: {{- .Values.cluster.entityOperator.userOperator.resources | toYaml | nindent 8 }}
      {{- end }}
  kafkaExporter:
    topicRegex: ".*"
    groupRegex: ".*"
    {{- if .Values.cluster.kafkaExporter.resources }}
    resources: {{- .Values.cluster.kafkaExporter.resources | toYaml | nindent 6 }}
    {{- end }}
