replicaCount: 1

image:
  name: coredns/coredns
  tag: "1.8.5"
  pullPolicy: IfNotPresent

service:
  type: LoadBalancer
  loadBalancerIP: 172.18.0.20
  ports:
    dns-tcp:
      port: 53
      protocol: TCP
#      nodePort: 30053
    dns-udp:
      port: 53
      protocol: UDP
#      nodePort: 30053

dnsRecords:
  sc.garagen: 172.18.0.19
