config: {}
  # HTTP proxy server Argo should use.
  # http_proxy: http://1.2.3.4:80
  # Service subnet which shouldn't be proxied
  # serviceSubnet: 10.96.0.0/12

argo-cd:
  server:
    envFrom:
      - configMapRef:
          name: argo-cd-proxy-config
  repoServer:
    envFrom:
      - configMapRef:
          name: argo-cd-proxy-config
