apiVersion: v1
kind: Service
metadata:
  name: {{ include "chart.fullname" . }}
  labels:
    {{- include "chart.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  clusterIP: None
  ports:
    - port: {{ .Values.service.port }}
      protocol: {{ .Values.service.protocol }}
      name: ntp
  selector:
    app.kubernetes.io/component: ntp-server
    {{- include "chart.selectorLabels" . | nindent 4 }}
