apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "fwd-proxy.fullname" . }}-webserver
  labels:
    {{- include "fwd-proxy.labels" . | nindent 4 }}
data:
  nginx.conf: | 
    {{- .Files.Get "config/nginx.conf" | nindent 4 }}
