apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "fwd-proxy.fullname" . }}
  labels:
    {{- include "fwd-proxy.labels" . | nindent 4 }}
data:
  envoy.yaml: | 
    {{- .Files.Get "config/envoy.yaml" | nindent 4 }}
