apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "fwd-proxy.fullname" . }}-example-html
  labels:
    {{- include "fwd-proxy.labels" . | nindent 4 }}
data:
  example.html: | 
    {{- .Files.Get "test/example.html" | nindent 4 }}

