apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "fwd-proxy.fullname" . }}
  labels:
    {{- include "fwd-proxy.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "fwd-proxy.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        checksum/configmap: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
        checksum/configmap-tls: {{ include (print $.Template.BasePath "/configmap-tls.yaml") . | sha256sum }}
      {{- with .Values.podAnnotations }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "fwd-proxy.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: envoyproxy
          securityContext:
            {{- toYaml .Values.envoyproxy.securityContext | nindent 12 }}
          image: "{{ .Values.envoyproxy.image.repository }}:{{ .Values.envoyproxy.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.envoyproxy.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 10000
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /healthz
              port: http
          resources:
            {{- toYaml .Values.envoyproxy.resources | nindent 12 }}
          volumeMounts:
            - mountPath: /etc/envoy/envoy.yaml
              name: config
              subPath: envoy.yaml
        - name: caddy
          securityContext:
            {{- toYaml .Values.caddy.securityContext | nindent 12 }}
          image: "{{ .Values.caddy.image.repository }}:{{ .Values.caddy.image.tag }}"
          imagePullPolicy: {{ .Values.caddy.image.pullPolicy }}
          livenessProbe:
            httpGet:
              path: /healthz
              port: 80
          resources:
            {{- toYaml .Values.caddy.resources | nindent 12 }}
          volumeMounts:
            - mountPath: /etc/caddy/Caddyfile
              name: config
              subPath: Caddyfile
            - mountPath: /data/caddy/pki/authorities/local/root.crt
              name: root-ssl
              subPath: root.crt
            - mountPath: /data/caddy/pki/authorities/local/root.key
              name: root-ssl
              subPath: root.key
      volumes:
        - name: config
          configMap:
            name: {{ include "fwd-proxy.fullname" . }}
        {{- if .Values.certificate -}}
        {{- if .Values.key -}}
        - name: root-ssl
          secret:
            secretName: {{ include "fwd-proxy.fullname" . }}
            items:
              - key: root_ca.crt
                path: root.crt
              - key: root_ca.key
                path: root.key
        {{- end -}}
        {{- end -}}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
