apiVersion: v1
kind: Service
metadata:
  name: {{ include "fwd-proxy.fullname" . }}
  labels:
    {{- include "fwd-proxy.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 10000
      protocol: TCP
      name: http
      nodePort: {{ .Values.service.nodePort }}
  selector:
    {{- include "fwd-proxy.selectorLabels" . | nindent 4 }}
