apiVersion: v1
kind: Service
metadata:
  name: {{ include "fwd-proxy.fullname" . }}-webserver
  labels:
    {{- include "fwd-proxy.labels" . | nindent 4 }}
spec:
  type: {{ .Values.webserver.service.type }}
  ports:
    - port: {{ .Values.webserver.service.port }}
      targetPort: 80
      protocol: TCP
      name: http
  selector:
    {{- include "fwd-proxy.selectorLabels" . | nindent 4 }}
