---
apiVersion: v2
name: kafka
description: A Helm chart for Kubernetes
type: application
version: 2.0.0

dependencies:
  - name: strimzi-kafka-operator
    version: "0.31.1"
    repository: "https://strimzi.io/charts/"
    condition: strimzi-kafka-operator.enabled
  - name: prometheus-kafka-exporter
    version: "1.1.0"
    repository: "https://prometheus-community.github.io/helm-charts"
    condition: prometheus-kafka-exporter.enabled
