{{- if .Values.networkPolicy.enabled -}}
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ template "helper.networkPolicy.name" . }}
  labels:
    {{- include "helper.labels" . | nindent 4 }}
    {{- if .Values.networkPolicy.labels }}
    {{- toYaml .Values.networkPolicy.labels | nindent 4 }}
    {{- end }}
  {{- if .Values.networkPolicy.annotations }}
  annotations:
  {{- range $key, $value := .Values.networkPolicy.annotations }}
    {{ $key }}: {{ $value | quote }}
  {{- end }}
  {{- end }}
spec:
{{ toYaml .Values.networkPolicy.spec | indent 2 }}
{{- end -}}
