{{if .Values.localStorageClass.enabled }}
apiVersion: v1
kind: PersistentVolume
metadata:
  name: local-pv
spec:
  storageClassName: local-storage
  capacity:
    storage: 1G
  accessModes:
      - ReadWriteMany
      - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  local:
    path: {{ .Values.localStorageClass.path }}
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - {{ .Values.localStorageClass.nodeName }}
{{ end }}
