on: 
  schedule:
    - cron:  '0 0 * * 0'

jobs:
  generate-matrix: 
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: ./charts/
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - name: Check dependencies action checkout step
        uses: actions/checkout@v2
        id: check-dependencies
      - name: set-matrix
        id: set-matrix
        run: |
          ARRAYSTART="{\"path\": [\""
          ARRAYLIST=$(echo *)
          ARRAYLIST="${ARRAYLIST// /\",\"}"
          ARRAYEND="\"]}"
          JSONSTRING="${ARRAYSTART}${ARRAYLIST}${ARRAYEND}"
          echo "::set-output name=matrix::$JSONSTRING"
  check-dependencies:
    needs: generate-matrix
    runs-on: ubuntu-latest
    name: Check dependencies
    strategy: 
      matrix: ${{ fromJson(needs.generate-matrix.outputs.matrix) }}
    steps:
      - name: Check dependencies action checkout step
        uses: actions/checkout@v2
        id: check-dependencies

      - name: Install yq
        run: sudo snap install yq
      
      - name: Run script
        id: run-script
        working-directory: ./charts/${{ matrix.path }}/chart
        run: | 
          ./../../../ci/helm-dependency-version-checker/entrypoint.sh
          helm dependency update
          rm -rf charts/

      - name: Commit changes
        if: ${{ steps.run-script.outputs.dependencies-changed > 0 }}
        working-directory: ./charts/${{ matrix.path }}/chart
        run: | 
          git config --global user.email "dependabot@dependabot.com"
          git config --global user.name "dependabot"
          git add -A
          git commit -m "${{ matrix.path }}: Update dependency ${{ steps.run-script.outputs.name }} version from ${{ steps.run-script.outputs.version }} to ${{ steps.run-script.outputs.highestversion }}"

      - name: Create pull request
        if: ${{ steps.run-script.outputs.dependencies-changed == 1 }}
        uses: peter-evans/create-pull-request@v3
        with: 
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ matrix.path }}-dep-upgrade-${{ steps.run-script.outputs.version }}-to-${{ steps.run-script.outputs.highestversion }}
          base: main
          delete-branch: true
          title: Dependency update ${{ steps.run-script.outputs.name }} from ${{ steps.run-script.outputs.version }} to ${{ steps.run-script.outputs.highestversion }}.
          body: "There is a dependency update for the dependency ${{ steps.run-script.outputs.name }} version ${{ steps.run-script.outputs.version }} => ${{ steps.run-script.outputs.highestversion }}. 
                  \n\n You can find the patch notes at the source URL: ${{ steps.run-script.outputs.url }}"
          labels: Automatic
          reviewers: jaxels10,klausenbusk,jacobcrawford,SomeFriendlyGhost,skovbakke

      - name: Create pull request
        if: ${{ steps.run-script.outputs.dependencies-changed > 1 }}
        uses: peter-evans/create-pull-request@v3
        with: 
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ matrix.path }}-multiple-dep-upgrade
          base: main
          delete-branch: true
          title: Multiple dependency updates for ${{ matrix.path }}.
          body: "There are dependency updates for the chart ${{ matrix.path }}."
          labels: Automatic
          reviewers: jaxels10,klausenbusk,jacobcrawford,SomeFriendlyGhost,skovbakke
