name: Lint and Test Charts

on: pull_request

jobs:
  lint-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          path: yamllint
          repository: distributed-technologies/gha-yamllint

      - name: Set up python
        uses: actions/setup-python@v2
        with:
          python-version: 3.7

      - name: Setup Chart Linting
        id: lint
        uses: helm/chart-testing-action@v2.1.0

      - name: List changed charts
        id: list-changed
        run: |
          ## If executed with debug this won't work anymore
          changed=$(ct --config ./.github/configs/ct-lint.yaml list-changed)
          charts=$(echo "$changed" | tr '\n' ' ' | xargs)
          if [[ -n "$changed" ]]; then
            echo "::set-output name=changed::true"
            echo "::set-output name=changed_charts::$charts"
          fi

      - name: Run chart-testing (lint)
        run: ct lint --debug --config ./.github/configs/ct-lint.yaml --lint-conf ./yamllint/config.yaml

      - name: Setup Minikube
        uses: manusa/actions-setup-minikube@v2.7.0
        with:
          minikube version: "v1.27.1"
          kubernetes version: "v1.25.0"
          github token: ${{ secrets.GITHUB_TOKEN }}

      - name: Run chart-testing (install)
        run: ct install --config ./.github/configs/ct-install.yaml --upgrade --helm-extra-args "--timeout 7200s"
        if: steps.list-changed.outputs.changed == 'true'
