---
name: Chart Publish
on:
  push:
    branches: [ main ]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Install Helm
        uses: azure/setup-helm@v1

      - name: Add dependency chart repos
        run: |
          helm repo add argo https://argoproj.github.io/argo-helm
          helm repo add stable https://charts.helm.sh/stable
          helm repo add repo https://distributed-technologies.github.io/helm-repository/
          helm repo add rook https://charts.rook.io/release
          helm repo add cache https://t83714.github.io/docker-registry-mirror
          helm repo add grafana https://grafana.github.io/helm-charts
          helm repo add harbor https://helm.goharbor.io
          helm repo add jaeger https://jaegertracing.github.io/helm-charts
          helm repo add common https://charts.bitnami.com/bitnami
          helm repo add kafka https://strimzi.io/charts/
          helm repo add kafkaexport https://prometheus-community.github.io/helm-charts
          helm repo add cp https://confluentinc.github.io/cp-helm-charts/
          helm repo add thanos https://kubernetes-charts.banzaicloud.com
          helm repo add traefik https://helm.traefik.io/traefik
          helm repo add vault https://helm.releases.hashicorp.com

      - name: Configure Git
        run: |
          git config user.name "Bot"
          git config user.email "${{ secrets.BOTEMAIL }}"  
          
      ## This is required to consider the old Circle-CI Index and to stay compatible with all the old releases.
      - name: Fetch current Chart Index 
        run: |
          git checkout origin/gh-pages index.yaml

      - name: Run chart-releaser
        uses: helm/chart-releaser-action@v1.2.0
        with: 
          config: "./.github/configs/cr.yaml"
          charts_dir: charts/*
        env:
          CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
