name: Test the setup af helm server

on: 
  pull_request:
    paths:
      - 'charts/artifact-registry/**'

jobs:
  test-helm-server-can-pull:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Make chart dir
        run: mkdir /home/runner/charts

      - name: Setup test
        run: mkdir gh-test && cd gh-test && helm create chart
      
      - name: Package helm
        run: cd gh-test && helm package chart

      - name: Create index and move
        run: cd gh-test && helm repo index . && mv * /home/runner/charts

      - name: Create k8s Kind Cluster
        uses: helm/kind-action@v1.2.0
        with: 
         config: "charts/artifact-registry/test/kind.yaml" 

      - name: Install LB to expose the Helm server 
        run: | 
          helm install --set ipRangeStart=172.18.0.10 \
            --set ipRangeStop=172.18.0.20  \
            --set imagePullPolicy=Always \
            lb https://github.com/distributed-technologies/services-loadbalancer/releases/download/v0.1.3/default.mukube-loadbalancer-v0.1.3.tgz
      
      - name: Install Helm Server
        run: helm install helm-server charts/artifact-registry/chart/ --values charts/artifact-registry/test/values.yaml

      - name: Wait for Helm registry
        run: kubectl wait --for=condition=ready pod -l app=helm-server --timeout=60s

      - name: Wait
        run: ./charts/artifact-registry/wait_for_ip.sh helm-server-service
      
      - name: Test Helm Registry
        run: helm repo add test-registry http://172.18.0.10 && helm install test-registry/chart --generate-name
