name: Test the setup af Image Registry

on: 
  pull_request:
    paths:
      - 'charts/artifact-registry/**'

jobs:
  test-helm-server-can-pull:
    runs-on: ubuntu-latest
    steps:

      - name: Make cert dir
        run: mkdir /home/runner/certs

      - name: Generate certificate
        run: | 
          openssl req -newkey rsa:4096 -nodes -sha256 -keyout /home/runner/certs/domain.key \
            -addext "subjectAltName = IP:172.18.0.11" \
            -x509 \
            -days 365 \
            -out /home/runner/certs/domain.crt \
            -subj "/C=te/ST=st/L=te/O=st/OU=te/CN=172.18.0.11"
      
      - name: Make trusted cert dir for docker
        run: sudo mkdir /etc/docker/certs.d/172.18.0.11:443/ -p

      - name: Copy trusted cert
        run: sudo cp /home/runner/certs/domain.crt /etc/docker/certs.d/172.18.0.11:443/ca.crt

      - uses: actions/checkout@v2

      - name: Create k8s Kind Cluster
        uses: helm/kind-action@v1.2.0 

      - name: Install LB to expose the Helm server 
        run: | 
          helm install --set ipRangeStart=172.18.0.10 \
            --set ipRangeStop=172.18.0.20  \
            --set imagePullPolicy=Always \
            lb https://github.com/distributed-technologies/services-loadbalancer/releases/download/v0.1.3/default.mukube-loadbalancer-v0.1.3.tgz
      
      - name: Install Artifact registry
        run: helm install artifact-registry charts/artifact-registry/chart/ --values charts/artifact-registry/test/values.yaml

      - name: Wait for Image Registry
        run: kubectl wait --for=condition=ready pod -l app=image-registry --timeout=120s

      - name: Wait
        run: ./charts/artifact-registry/wait_for_ip.sh image-registry-service

      - name: Test registry (push)
        run: |
          docker pull alpine 
          docker tag alpine 172.18.0.11:443/alpine 
          docker push 172.18.0.11:443/alpine
      
      - name: Test registry (pull)
        run: |
          docker pull 172.18.0.11:443/alpine
