name: Test the setup af Image Registry

on: 
  pull_request:
    paths:
      - 'charts/artifact-registry/**'

jobs:
  test-helm-server-can-pull:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Create k8s Kind Cluster
        uses: helm/kind-action@v1.2.0
        with: 
         config: "charts/artifact-registry/test/kind.yaml" 

      - name: Install LB to expose the Helm server 
        run: | 
          helm install --set ipRangeStart=172.18.0.10 \
            --set ipRangeStop=172.18.0.20  \
            --set imagePullPolicy=Always \
            lb https://github.com/distributed-technologies/services-loadbalancer/releases/download/v0.1.3/default.mukube-loadbalancer-v0.1.3.tgz
      
      - name: Install Artifact registry
        run: helm install artifact-registry charts/artifact-registry/chart/ --values charts/artifact-registry/test/values.yaml

      - name: Wait for Image Registry
        run: kubectl wait --for=condition=ready pod -l app=image-registry --timeout=120s

      - name: Wait
        run: ./charts/artifact-registry/wait_for_ip.sh image-registry-service

      - name: Test registry (push)
        run: |
          podman pull alpine 
          podman tag alpine 172.18.0.11:80/alpine 
          podman push 172.18.0.11:80/alpine --tls-verify=false
      
      - name: Test registry (pull)
        run: |
          podman pull 172.18.0.11:80/alpine --tls-verify=false
