apiVersion: v1
kind: ConfigMap
metadata:
  name: argo-cd-proxy-config
  labels:
    {{- include "chart.labels" . | nindent 4 }}
data:
  {{- if .Values.config.httpProxy }}
  http_proxy: {{ .Values.config.httpProxy | quote }}
  https_proxy: {{ .Values.config.httpProxy | quote }}
  {{- $services := list "argocd-application-controller" "argocd-dex-server" "argocd-redis" "argocd-repo-server" "argocd-server" "redis-ha-haproxy" }}
  {{- range $services -}}
  {{- $services = append $services (printf "%s-%s" ($.Release.Name | trunc 63 | trimSuffix "-") .) -}}
  {{- $services = rest $services -}}
  {{- end }}
  no_proxy: {{ printf "%s,%s" (join "," $services) (.Values.config.serviceSubnet) | quote }}
  {{- end -}}
